name: Main workflow

on:
  push:
    paths-ignore:
      - 'doc/**'
      - '**/*.md'
      - 'LICENSE'
      - 'example/**'
      - '.gitignore'
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '**/*.md'
      - 'LICENSE'
      - 'example/**'
      - '.gitignore'


jobs:
  validate:
    strategy:
      matrix:
        python: [ '3.11', '3.12' ]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Run tests
        run: python tests/run_tests.py
